
--Author: Kevin Thomas, Registrar
--Date:  20 FEB 2024
--Purpose: This script returns students that have GRNs but have 
--         had a bursar's office hold ended SOAHOLD within the last week;

--NOTE 1:  This is hard coded to look for 202380 and forward.  

--desc SPRHOLD  
--desc shrdgcm

SELECT SPRIDEN.SPRIDEN_ID        AS SCHOOL_ID,
  SPRIDEN.SPRIDEN_LAST_NAME      AS LAST_NAME,
  SPRIDEN.SPRIDEN_FIRST_NAME     AS FIRST_NAME,
  SHRDGMR.SHRDGMR_TERM_CODE_GRAD AS GRAD_TERM,
  SHRDGMR.SHRDGMR_GRST_CODE      AS GRADUATION_STATUS,
  SHRDGMR.SHRDGMR_GRAD_DATE      AS GRADUATION_DATE,
  SPRHOLD_HLDD_Code as "Hold Code",
  SPRHOLD_TO_DATE as "Hold Ended"
  
FROM SHRDGMR,
  SPRIDEN,
  SOVLCUR,
  SPRHOLD,
  shrdgcm
WHERE SHRDGMR.SHRDGMR_PIDM          = SOVLCUR.SOVLCUR_PIDM
AND SHRDGMR.SHRDGMR_SEQ_NO          = SOVLCUR.SOVLCUR_KEY_SEQNO
AND SHRDGMR.SHRDGMR_PIDM            = SPRIDEN.SPRIDEN_PIDM
and shrdgcm_pidm = spriden_pidm
and shrdgmr_seq_no = SHRDGCM_DGMR_SEQ_NO
AND SPRHOLD_pidm = shrdgmr_pidm
AND SHRDGMR.SHRDGMR_TERM_CODE_GRAD > =  '202380'
AND SHRDGMR.SHRDGMR_GRST_CODE      = 'GRN'
AND SOVLCUR.SOVLCUR_CURRENT_IND     = 'Y'
AND SOVLCUR.SOVLCUR_ACTIVE_IND      = 'Y'
AND SOVLCUR.SOVLCUR_LMOD_CODE       = 'OUTCOME'
AND SPRIDEN.SPRIDEN_CHANGE_IND     IS NULL
AND SHRDGMR.SHRDGMR_DEGC_CODE      IN ('AS', 'AAS', 'AA', 'CERT')
AND SPRHOLD_HLDD_CODE = 'BO'
and SPRHOLD_TO_DATE < SYSDATE
--AND SORTEST_TEST_SCORE = 'Y'
--AND SORTEST_TEST_DATE > SYSDATE - 7 
--GROUP BY 
--SPRIDEN.SPRIDEN_ID, SPRIDEN.SPRIDEN_LAST_NAME, SPRIDEN.SPRIDEN_FIRST_NAME, SHRDGMR.SHRDGMR_TERM_CODE_GRAD, 
--SHRDGMR.SHRDGMR_GRST_CODE, SHRDGMR.SHRDGMR_GRAD_DATE
ORDER BY GRAD_TERM,
  LAST_NAME,
  FIRST_NAME;

