
--USE THIS SCRIPT TO GET CALL CARDS FOR GRADUATION...this will does not include GRN students...see below..kt...3/24/21
--TO FIND STUDENTS THAT HAVE THE MILT ATTRIBUTE ON SGASADD, UNCOMMENT OUT SGRSATT LINES
--GPA has been truncated after the 2nd degit past the decimal


SELECT SPRIDEN_ID AS STUDENT_ID, 
--       SPRIDEN_PIDM, 
       SPRIDEN_LAST_NAME AS LAST_NAME, SPRIDEN_FIRST_NAME AS FIRST_NAME,
       shrlgpa_gpa_type_ind as GPA_TYPE, trunc (SHRLGPA_GPA,2) AS "TRUNCATED GPA",
       SHRDGMR_SEQ_NO AS DEG_SEQ, 
       SHRDGMR_TERM_CODE_GRAD AS GRAD_TERM, 
       SHRDGMR_GRST_CODE AS GRAD_STATUS, 
       --SHRDGMR_GRAD_DATE AS GRAD_DATE, 
       --SOVLCUR_TERM_CODE_CTLG AS CATALOG,
       SHRDGMR_DEGC_CODE AS DEGREE,
       SHRDGMR_MAJR_CODE_1 AS MAJOR_1, SHRDGMR_MAJR_CODE_CONC_1 AS CONC_1--,
--       SHRDGMR_MAJR_CODE_2 AS MAJOR_2, SHRDGMR_MAJR_CODE_CONC_2 AS CONCENTRATION_2 
      -- SGRSATT_ATTS_CODE AS MILLITARY
FROM SHRDGMR, SOVLCUR OUTTER, SPRIDEN, SHRLGPA--, SGRSATT
WHERE 
      SHRDGMR_TERM_CODE_GRAD IN (:Term_1, :Term_2, :Term_3) 
      --SHRDGMR_TERM_CODE_GRAD = ':Term_1'
      --SHRDGMR_TERM_CODE_GRAD IN (:Term_1, :Term_2)  
  AND SHRDGMR_PIDM = SOVLCUR_PIDM AND SHRDGMR_SEQ_NO = SOVLCUR_KEY_SEQNO AND SOVLCUR_CURRENT_IND = 'Y' AND SOVLCUR_ACTIVE_IND = 'Y' AND SOVLCUR_LMOD_CODE = 'OUTCOME'
  AND SHRDGMR_PIDM = SPRIDEN_PIDM 
  AND SHRDGMR_PIDM = SHRLGPA_PIDM
 -- AND SHRDGMR_PIDM = SGRSATT_PIDM
  AND SPRIDEN_CHANGE_IND IS  NULL
-- AND SHRDGMR_GRST_CODE IS NOT NULL   --Commented out as this will include GRN students...k.t. 3/24/21
AND SHRDGMR_GRST_CODE != 'GRN'
  --Added GPA Information; Type = I (Institutional), T (Transfer), or O for Overall (UG Combined (T and I))
  and   shrlgpa_levl_code = 'UG'
  and   shrlgpa_gpa_type_ind = 'O'
  --Added Next Line of Code to exclude the new academic certificates on 4/10/12...LLW 
  and   SHRDGMR_DEGC_CODE NOT IN ('ACRT1','ACRT2')
--  and   SHRDGMR_DEGC_CODE = Degree
--  and   SHRDGMR_MAJR_CODE_1 = :Major
  --and SHRDGMR_MAJR_CODE_2 is not null
 -- and SGRSATT_ATTS_CODE = 'MILT'
ORDER BY SHRDGMR_TERM_CODE_GRAD,SHRDGMR_DEGC_CODE,SHRDGMR_MAJR_CODE_1,SPRIDEN_LAST_NAME,SPRIDEN_FIRST_NAME;
