
SELECT 
    s.SPRIDEN_ID AS Student_ID,
    NVL(c.SCBCRSE_SURROGATE_ID, sec.SSBSECT_CRN) AS Class_History_key, --Unique ID to create entity row key in Slate
    c.SCBCRSE_SUBJ_CODE || c.SCBCRSE_CRSE_NUMB || c.SCBCRSE_EFF_TERM AS course_history_id_fk,    --Unique ID to match data to the Catalog dataset in Slate
    r.SFRSTCR_GRDE_CODE AS Grade,
    t.STVTERM_DESC AS Term,
    'NSCC' AS Credit_Type    
FROM SFRSTCR r
JOIN SSBSECT sec 
    ON sec.SSBSECT_CRN = r.SFRSTCR_CRN 
   AND sec.SSBSECT_TERM_CODE = r.SFRSTCR_TERM_CODE
JOIN STVTERM t 
    ON t.STVTERM_CODE = r.SFRSTCR_TERM_CODE
JOIN SPRIDEN s 
    ON s.SPRIDEN_PIDM = r.SFRSTCR_PIDM 
   AND s.SPRIDEN_CHANGE_IND IS NULL
JOIN GOVADID g
	ON g.GOVADID_PIDM = s.SPRIDEN_PIDM
	AND g.GOVADID_ADID_CODE = 'SLID'
LEFT JOIN SCBCRSE c 
    ON c.SCBCRSE_SUBJ_CODE = sec.SSBSECT_SUBJ_CODE
   AND c.SCBCRSE_CRSE_NUMB = sec.SSBSECT_CRSE_NUMB
   AND c.SCBCRSE_EFF_TERM = (
       SELECT MAX(x.SCBCRSE_EFF_TERM)
       FROM SCBCRSE x
       WHERE x.SCBCRSE_SUBJ_CODE = sec.SSBSECT_SUBJ_CODE
         AND x.SCBCRSE_CRSE_NUMB = sec.SSBSECT_CRSE_NUMB
         AND x.SCBCRSE_EFF_TERM <= sec.SSBSECT_TERM_CODE
   )
WHERE r.SFRSTCR_GRDE_CODE IS NOT NULL
 
UNION ALL
 
-- Transfer Coursework
SELECT 
    s.SPRIDEN_ID AS Student_ID,
    r.SHRTRCE_SURROGATE_ID AS Class_History_key,
    c.SCBCRSE_SUBJ_CODE || c.SCBCRSE_CRSE_NUMB || c.SCBCRSE_EFF_TERM AS course_history_id_fk,    
    r.SHRTRCE_GRDE_CODE AS Grade,
    'TRANSFER' AS Term,
    'Transfer' AS Credit_Type    
FROM SHRTRCE r
JOIN SPRIDEN s 
    ON s.SPRIDEN_PIDM = r.SHRTRCE_PIDM 
   AND s.SPRIDEN_CHANGE_IND IS NULL
JOIN GOVADID g
ON g.GOVADID_PIDM = s.SPRIDEN_PIDM
AND g.GOVADID_ADID_CODE = 'SLID'
LEFT JOIN SCBCRSE c 
    ON c.SCBCRSE_SUBJ_CODE = r.SHRTRCE_SUBJ_CODE
   AND c.SCBCRSE_CRSE_NUMB = r.SHRTRCE_CRSE_NUMB
   AND c.SCBCRSE_EFF_TERM = (
       SELECT MAX(x.SCBCRSE_EFF_TERM)
       FROM SCBCRSE x
       WHERE x.SCBCRSE_SUBJ_CODE = r.SHRTRCE_SUBJ_CODE
         AND x.SCBCRSE_CRSE_NUMB = r.SHRTRCE_CRSE_NUMB
   )
WHERE r.SHRTRCE_GRDE_CODE IS NOT NULL;