SELECT DISTINCT 
S.SPRIDEN_ID AS "ID",
S.SPRIDEN_LAST_NAME AS "LAST_NAME",
S.SPRIDEN_FIRST_NAME AS "FIRST_NAME",
H.SPRHOLD_FROM_DATE AS "HOLD_FROM_DATE",
H.SPRHOLD_ORIG_CODE AS "INSTITUTION_CODE"

FROM SPRIDEN S
JOIN SPRHOLD H ON H.SPRHOLD_PIDM = S.SPRIDEN_PIDM
AND H.SPRHOLD_HLDD_CODE = 'XR'
AND H.SPRHOLD_TO_DATE > SYSDATE


WHERE S.SPRIDEN_CHANGE_IND IS NULL

ORDER BY S.SPRIDEN_LAST_NAME, S.SPRIDEN_FIRST_NAME