SELECT DISTINCT 
S.SPRIDEN_ID AS "ID",
S.SPRIDEN_LAST_NAME AS "LAST_NAME",
S.SPRIDEN_FIRST_NAME AS "FIRST_NAME",
H.SPRHOLD_FROM_DATE AS "HOLD_FROM_DATE",
H.SPRHOLD_ORIG_CODE AS "INSTITUTION_CODE",

CASE 
WHEN H.SPRHOLD_ORIG_CODE = 'SD02'
THEN 'Columbia_State'
WHEN H.SPRHOLD_ORIG_CODE = 'SD03'
THEN 'T_Athens'
WHEN H.SPRHOLD_ORIG_CODE = 'SD04'
THEN 'T_Covington'
WHEN H.SPRHOLD_ORIG_CODE = 'SD05'
THEN 'T_Crossville'
WHEN H.SPRHOLD_ORIG_CODE = 'SD06'
THEN 'T_Dickson'
WHEN H.SPRHOLD_ORIG_CODE = 'SD07'
THEN 'T_Elizabethton'
WHEN H.SPRHOLD_ORIG_CODE = 'SD08'
THEN 'T_Harriman'
WHEN H.SPRHOLD_ORIG_CODE = 'SD09'
THEN 'T_Hartsville'
WHEN H.SPRHOLD_ORIG_CODE = 'SD10'
THEN 'T_Hohenwald'
WHEN H.SPRHOLD_ORIG_CODE = 'SD12'
THEN 'T_Jacksboro'
WHEN H.SPRHOLD_ORIG_CODE = 'SD13'
THEN 'T_Jackson'
WHEN H.SPRHOLD_ORIG_CODE = 'SD15'
THEN 'T_Jackson_State'
WHEN H.SPRHOLD_ORIG_CODE = 'SD16'
THEN 'T_Knoxville'
WHEN H.SPRHOLD_ORIG_CODE = 'SD17'
THEN 'T_Livingston'
WHEN H.SPRHOLD_ORIG_CODE = 'SD18'
THEN 'T_McKenzie'
WHEN H.SPRHOLD_ORIG_CODE = 'SD19'
THEN 'T_McMinnville'
WHEN H.SPRHOLD_ORIG_CODE = 'SD20'
THEN 'T_Memphis'
WHEN H.SPRHOLD_ORIG_CODE = 'SD21'
THEN 'T_Morristown'
WHEN H.SPRHOLD_ORIG_CODE = 'SD22'
THEN 'T_Murfreesboro'
WHEN H.SPRHOLD_ORIG_CODE = 'SD25'
THEN 'T_Nashville'
WHEN H.SPRHOLD_ORIG_CODE = 'SD26'
THEN 'T_Newbern'
WHEN H.SPRHOLD_ORIG_CODE = 'SD27'
THEN 'T_Oneida'
WHEN H.SPRHOLD_ORIG_CODE = 'SD28'
THEN 'T_Paris'
WHEN H.SPRHOLD_ORIG_CODE = 'SD29'
THEN 'T_Pulaski'
WHEN H.SPRHOLD_ORIG_CODE = 'SD34'
THEN 'T_Ripley'
WHEN H.SPRHOLD_ORIG_CODE = 'SD35'
THEN 'T_Crump'
WHEN H.SPRHOLD_ORIG_CODE = 'SD36'
THEN 'T_Shelbyville'
WHEN H.SPRHOLD_ORIG_CODE = 'SD38'
THEN 'T_Whiteville'
WHEN H.SPRHOLD_ORIG_CODE = 'SD40'
THEN 'T_Chattanooga'
WHEN H.SPRHOLD_ORIG_CODE = 'SD51'
THEN 'Cleveland_State'
WHEN H.SPRHOLD_ORIG_CODE = 'SD59'
THEN 'Dyersburg_State'
WHEN H.SPRHOLD_ORIG_CODE = 'SD60'
THEN 'Motlow_State'
WHEN H.SPRHOLD_ORIG_CODE = 'SD61'
THEN 'Walters_State'
WHEN H.SPRHOLD_ORIG_CODE = 'SD63'
THEN 'Volunteer_State'
WHEN H.SPRHOLD_ORIG_CODE = 'SD64'
THEN 'Roane_State'
WHEN H.SPRHOLD_ORIG_CODE = 'SD65'
THEN 'Chattanooga State'
WHEN H.SPRHOLD_ORIG_CODE = 'SD70'
THEN 'Southwest'
WHEN H.SPRHOLD_ORIG_CODE = 'SD73'
THEN 'Northwest_State'
WHEN H.SPRHOLD_ORIG_CODE = 'SD90'
THEN 'Nashville_State'
WHEN H.SPRHOLD_ORIG_CODE = 'SD96'
THEN 'Pellissippi'
Else Null
END as "INSTITUTION"

FROM SPRIDEN S

JOIN SPRHOLD H ON H.SPRHOLD_PIDM = S.SPRIDEN_PIDM
AND H.SPRHOLD_HLDD_CODE = 'XO'
AND H.SPRHOLD_TO_DATE > SYSDATE


WHERE S.SPRIDEN_CHANGE_IND IS NULL


ORDER BY S.SPRIDEN_LAST_NAME, S.SPRIDEN_FIRST_NAME