--Parameters
-- 
ACCEPT GradYear prompt 'Enter Spring Grad Year(Like 2008 for the reporting period 2007-2008): '
-- 
ACCEPT SystemCode prompt 'Enter System Code (It should be one digit): '
 --  
ACCEPT InstitutionCode prompt 'Enter Institution Code(It should be two digits): '
--Set to run from command line.
SET ECHO OFF
SET VERIFY OFF
SET FEEDBACK OFF
SET HEADING OFF
SET PAGESIZE 0
SET LINESIZE 500
SET SPACE 0
SET COLSEP '|'
--Set columns for SQL Plus in Banner 8
COLUMN SYSTEM_CODE FORMAT A1
COLUMN SCHOOL_CODE FORMAT A2
COLUMN LOCATION FORMAT A2
COLUMN STUDENT_ID_NUMBER FORMAT A9
COLUMN TERM_OF_AWARD FORMAT A1
COLUMN YEAR_OF_AWARD FORMAT A4         --09/01/2016 modified length to 4 char
COLUMN TERM_OF_COMPLETION FORMAT A1
COLUMN YEAR_OF_COMPLETION FORMAT A4    --09/01/2016 modified length to 4 char
COLUMN AWARD FORMAT A8
COLUMN FIRST_MAJOR_AREA FORMAT A10
COLUMN SECOND_MAJOR_AREA FORMAT A10
COLUMN GENDER FORMAT A1
COLUMN YEAR_OF_BIRTH FORMAT A4        --09/02/2016 modified length to 4 char
COLUMN RACE FORMAT A1
COLUMN PERMANENT_RESIDENCE FORMAT A5
COLUMN FEE_PAYING_STATUS FORMAT A1
COLUMN CITIZENSHIP_STATUS FORMAT A1
COLUMN FILLER_1 FORMAT A15
COLUMN ADDITIONAL_MAJOR_TYPE FORMAT A1
COLUMN FILLER_2 FORMAT A5
COLUMN HIGH_SCHOOL_DIPL_TYPE FORMAT A1
COLUMN HIGH_SCHOOL_CODE FORMAT A6
COLUMN HIGH_SCHOOL_GRAD_YEAR FORMAT A4
COLUMN HIGH_SCHOOL_RANK FORMAT A1
COLUMN HIGH_SCHOOL_GPA_GED FORMAT A3
COLUMN RESIDENT_STATUS_TUIT FORMAT A1
COLUMN PROGRAM_DELIVERY FORMAT A1
COLUMN REPORTING_YEAR FORMAT A4
COLUMN BANNER_ID FORMAT A9
COLUMN BANNER_GPA_TERM FORMAT A6
COLUMN BANNER_PIDM FORMAT A8
COLUMN FILLER_3 FORMAT A23
COLUMN ALL_COMB_HRS_ATMP FORMAT A5
COLUMN ALL_COMB_HRS_EARN FORMAT A5
COLUMN ALL_COMB_QUAL_HRS FORMAT A5
COLUMN ALL_COMB_QUAL_PTS FORMAT A6
COLUMN ALL_COMB_GPA FORMAT A4
COLUMN INST_COMB_HRS_ATMP FORMAT A5
COLUMN INST_COMB_HRS_EARN FORMAT A5
COLUMN INST_COMB_QUAL_HRS FORMAT A5
COLUMN INST_COMB_QUAL_PTS FORMAT A6
COLUMN INST_COMB_GPA FORMAT A4
COLUMN TRAN_COMB_HRS_ATMP FORMAT A5
COLUMN TRAN_COMB_HRS_EARN FORMAT A5
COLUMN TRAN_COMB_QUAL_HRS FORMAT A5
COLUMN TRAN_COMB_QUAL_PTS FORMAT A6
COLUMN TRAN_COMB_GPA FORMAT A4
COLUMN ALL_COLLEGE_HRS_ATMP FORMAT A5
COLUMN ALL_COLLEGE_HRS_EARN FORMAT A5
COLUMN ALL_COLLEGE_QUAL_HRS FORMAT A5
COLUMN ALL_COLLEGE_QUAL_PTS FORMAT A6
COLUMN ALL_COLLEGE_GPA FORMAT A4
COLUMN INST_COLLEGE_HRS_ATMP FORMAT A5
COLUMN INST_COLLEGE_HRS_EARN FORMAT A5
COLUMN INST_COLLEGE_QUAL_HRS FORMAT A5
COLUMN INST_COLLEGE_QUAL_PTS FORMAT A6
COLUMN INST_COLLEGE_GPA FORMAT A4
COLUMN TRAN_COLLEGE_HRS_ATMP FORMAT A5
COLUMN TRAN_COLLEGE_HRS_EARN FORMAT A5
COLUMN TRAN_COLLEGE_QUAL_HRS FORMAT A5
COLUMN TRAN_COLLEGE_QUAL_PTS FORMAT A6
COLUMN TRAN_COLLEGE_GPA FORMAT A4
COLUMN ETHNICITY FORMAT A1
COLUMN RACE_UNKNOWN FORMAT A2
COLUMN RACE_ALASKAN_NATIVE FORMAT A2
COLUMN RACE_AMERICAN_INDIAN FORMAT A2
COLUMN RACE_ASIAN FORMAT A2
COLUMN RACE_BLACK_AFRICAN_AM FORMAT A2
COLUMN RACE_WHITE FORMAT A2
COLUMN RACE_HAWAIIAN_PAC_ISL FORMAT A2
COLUMN FIRST_MAJOR_CODE FORMAT A4
COLUMN FIRST_CONC_CODE FORMAT A4
COLUMN FIRST_CONC_FED_CIP FORMAT A6
COLUMN SECOND_MAJOR_CODE FORMAT A4
COLUMN SECOND_CONC_CODE FORMAT A4
COLUMN SECOND_CONC_FED_CIP FORMAT A6
COLUMN REVERSETRANSFER_FLAG FORMAT A1 

--Spool to file.
SPOOL arfile.dat
--
SELECT DISTINCT 
SUBSTR('&SystemCode',1,1) SYSTEM_CODE,
SUBSTR('&InstitutionCode',1,2) SCHOOL_CODE,
CASE
    WHEN SUBSTR(Grads.SHRDGMR_CAMP_CODE,1,1) BETWEEN'A' AND 'W'
    THEN SUBSTR(Grads.SHRDGMR_CAMP_CODE,2,2)
    WHEN SUBSTR(Grads.SHRDGMR_CAMP_CODE,1,2) BETWEEN'01' AND '99'
    THEN '  '
END LOCATION,
CASE WHEN SPBPERS_SSN IS NULL THEN SPRIDEN_ID ELSE SPBPERS_SSN END STUDENT_ID_NUMBER,
DECODE(SUBSTR(Grads.SHRDGMR_TERM_CODE_GRAD,5,1),'8','1','1','3','5','4') TERM_OF_AWARD,
SUBSTR(Grads.SHRDGMR_TERM_CODE_GRAD,1,4) YEAR_OF_AWARD, --09/01/2016 modified to 4 char date
DECODE(SUBSTR(Grads.Term_Of_Completion,5,1),'8','1','1','3','5','4') TERM_OF_COMPLETION,
SUBSTR(Grads.Term_Of_Completion,1,4) YEAR_OF_COMPLETION ,--09/01/2016 modified to 4 char date
RPAD(STVDEGC_ACAT_CODE||(CASE WHEN Grads.SHRDGMR_DEGC_CODE IN('TCP', 'CRT1', 'CRT2', 'CRT3', 'CRT4') THEN 'C1'
      WHEN Grads.SHRDGMR_DEGC_CODE IN('ACRT1', 'ACRT2') THEN 'C2'
      WHEN Grads.SHRDGMR_DEGC_CODE IN('ACRT3', 'ACRT4') THEN 'C3'
      WHEN Grads.SHRDGMR_DEGC_CODE IN('GCRT', 'C441') THEN 'C4'
      ELSE Grads.SHRDGMR_DEGC_CODE END
),8) AWARD,
--Old code for award
--RPAD(STVDEGC_ACAT_CODE||Grads.SHRDGMR_DEGC_CODE,8) AWARD,
--
LPAD(DECODE(Grads.SHRDGMR_MAJR_CODE_1,'0000','U         ', DECODE(SUBSTR(S1.STVMAJR_CIPC_CODE,1,1),'U',S1.STVMAJR_CIPC_CODE, 'N',S1.STVMAJR_CIPC_CODE,SUBSTR(X1.SORXREF_EDI_VALUE,1,2)||S1.STVMAJR_CIPC_CODE
  ||SUBSTR(X1.SORXREF_EDI_VALUE,3,2))),10,'0') FIRST_MAJOR_AREA,
LPAD(DECODE(Grads.SHRDGMR_MAJR_CODE_1_2,'0000','U         ', DECODE(SUBSTR(S2.STVMAJR_CIPC_CODE,1,1),'U',S2.STVMAJR_CIPC_CODE, 'N',S2.STVMAJR_CIPC_CODE,SUBSTR(X2.SORXREF_EDI_VALUE,1,2)||S2.STVMAJR_CIPC_CODE
  ||SUBSTR(X2.SORXREF_EDI_VALUE,3,2))),10,'0') SECOND_MAJOR_AREA,
--RPAD(Grads.SHRDGMR_MAJR_CODE_1_2,10) "Second Major Area", --Old second major
  SPBPERS_SEX GENDER,
  TO_CHAR(SPBPERS_BIRTH_DATE,'YYYY') YEAR_OF_BIRTH,
  DECODE (SPBPERS_ETHN_CODE, '30', '1', '10', '2', '40', '3', '50', '4', '60', '5', '00', '6', '20', '7', ' ') RACE,
  CASE WHEN (TT.STAT_CODE = '47')  THEN TT.CNTY_CODE
  WHEN SUBSTR('&InstitutionCode',1,2) = '14' AND  TT.CNTY_CODE IN('21003','21035','21047','21141','21213','21219','21221') THEN TT.CNTY_CODE
      WHEN SUBSTR('&InstitutionCode',1,2) = '23' AND  TT.CNTY_CODE IN('37009','37011','37087','37115','37121','37189','37199','51105','51169','51191','51520') THEN TT.CNTY_CODE
      WHEN SUBSTR('&InstitutionCode',1,2) = '50' AND  TT.CNTY_CODE IN('21053','21057','21147','21171','21231') THEN TT.CNTY_CODE
      WHEN SUBSTR('&InstitutionCode',1,2) = '11' AND  TT.CNTY_CODE IN('05035','28033','28093','28137','28143') THEN TT.CNTY_CODE
      WHEN SUBSTR('&InstitutionCode',1,2) = '65' AND  TT.CNTY_CODE IN('01071','13047','13083','13111','13213','13295','13313') THEN TT.CNTY_CODE
      WHEN SUBSTR('&InstitutionCode',1,2) = '51' AND  TT.CNTY_CODE IN('13295','13313','13213','13111','13047') THEN TT.CNTY_CODE
      WHEN SUBSTR('&InstitutionCode',1,2) = '59' AND  TT.CNTY_CODE IN('05093','29069','29155') THEN TT.CNTY_CODE
      WHEN SUBSTR('&InstitutionCode',1,2) = '60' AND  TT.CNTY_CODE IN('01089','0107','01083') THEN TT.CNTY_CODE
      WHEN SUBSTR('&InstitutionCode',1,2) = '70' AND  TT.CNTY_CODE IN('05093','05035','28033','28093') THEN TT.CNTY_CODE
      WHEN SUBSTR('&InstitutionCode',1,2) = '73' AND  TT.CNTY_CODE IN('51191','51169','37121','37189') THEN TT.CNTY_CODE
      WHEN SUBSTR('&InstitutionCode',1,2) = '63' AND  TT.CNTY_CODE IN('21141','21213','21003') THEN TT.CNTY_CODE
      WHEN SUBSTR('&InstitutionCode',1,2) = '61' AND  TT.CNTY_CODE IN('51105','37075','37087','37115','37121','37173','37199') THEN TT.CNTY_CODE
      WHEN TT.STAT_CODE IS NULL THEN RPAD(TT.NATN_CODE,5) ELSE RPAD(TT.STAT_CODE,5)
  END PERMANENT_RESIDENCE,
  ' ' FEE_PAYING_STATUS,
  DECODE (SPBPERS_CITZ_CODE, 'Y', '1', 'P', '3', 'N', '2', 'R', '3', 'T', '2',' ') CITIZENSHIP_STATUS,
  '               ' FILLER_1,
  '1' ADDITIONAL_MAJOR_TYPE,
  '     ' FILLER_2,
  DECODE(SORHSCH_dplm_code, 'AC', 'E', 'CA', ' ', 'DE', ' ', 'EA', 'D', 'GE', 'C', 'GT', ' ', 'HD', 'H', 'HM', 'J', 'IB', 'A', 'JE', ' ', 'RD', 'A', 'SP', 'B',' ') HIGH_SCHOOL_DIPL_TYPE,
  DECODE(SORHSCH_SBGI_CODE,'UNKHS', '999999', SORHSCH_SBGI_CODE) HIGH_SCHOOL_CODE,
  TO_CHAR(SORHSCH_GRADUATION_DATE,'YYYY') HIGH_SCHOOL_GRAD_YEAR,
  CASE 
  WHEN SORHSCH_PERCENTILE BETWEEN 90 AND 100 THEN '1'
  WHEN SORHSCH_PERCENTILE BETWEEN 75 AND 89 THEN '2'
  WHEN SORHSCH_PERCENTILE BETWEEN 50 AND 74 THEN '3'
  WHEN SORHSCH_PERCENTILE BETWEEN 0 AND 49 THEN '4'
    ELSE '5'
    END HIGH_SCHOOL_RANK,
    RPAD(REPLACE(SORHSCH_GPA,'.'),3,'0') HIGH_SCHOOL_GPA_GED,
    SGBSTDN_RESD_CODE RESIDENT_STATUS_TUIT,
  ' ' PROGRAM_DELIVERY,
  Trim(&GradYear) REPORTING_YEAR,
  SPRIDEN_ID BANNER_ID,
  Grads.Term_Of_Completion BANNER_GPA_TERM,
  LPAD(Grads.SHRDGMR_PIDM,8) BANNER_PIDM,
  '      ' FILLER_3,
  LPAD(TO_CHAR(ROUND(Grads.OCHA,2)*100),5,'0') ALL_COMB_HRS_ATMP, --"Over Cmb Hours Attempted" 
  LPAD(TO_CHAR(ROUND(Grads.OCHE,2)*100),5,'0') ALL_COMB_HRS_EARN, --"Over Cmb Hours Earned"
  LPAD(TO_CHAR(ROUND(Grads.OCQA,2)*100),5,'0') ALL_COMB_QUAL_HRS, --"Over Cmb Quality Hours"
  LPAD(TO_CHAR(ROUND(Grads.OCQP,2)*100),6,'0') ALL_COMB_QUAL_PTS, --"Over Cmb Quality Points" 
  CASE WHEN Grads.OCGPA < 1 THEN LPAD(REPLACE(TO_CHAR(ROUND(Grads.OCGPA,3)),'.'),4,'0') ELSE RPAD(REPLACE(TO_CHAR(ROUND(Grads.OCGPA,3)),'.'),4,'0')  END  ALL_COMB_GPA, --"Over Cmb GPA"
  LPAD(TO_CHAR(ROUND(Grads.ICHA,2)*100),5,'0') INST_COMB_HRS_ATMP, --"Inst Cmb Hours Attempted"
  LPAD(TO_CHAR(ROUND(Grads.ICHE,2)*100),5,'0') INST_COMB_HRS_EARN, --"Inst Cmb Hours Earned"
  LPAD(TO_CHAR(ROUND(Grads.ICQA,2)*100),5,'0') INST_COMB_QUAL_HRS, --"Inst Cmb Quality Hours" 
  LPAD(TO_CHAR(ROUND(Grads.ICQP,2)*100),6,'0') INST_COMB_QUAL_PTS, --"Inst Cmb Quality Points"
  CASE WHEN Grads.iCGPA < 1 THEN LPAD(REPLACE(TO_CHAR(ROUND(Grads.ICGPA,3)),'.'),4,'0') ELSE RPAD(REPLACE(TO_CHAR(ROUND(Grads.ICGPA,3)),'.'),4,'0')  END  INST_COMB_GPA, --"Inst Cmb GPA"
  LPAD(TO_CHAR(ROUND(Grads.TCHA,2)*100),5,'0') TRAN_COMB_HRS_ATMP, --"Tran Cmb Hours Attempted", 
  LPAD(TO_CHAR(ROUND(Grads.TCHE,2)*100),5,'0') TRAN_COMB_HRS_EARN, --"Tran Cmb Hours Earned",  
  LPAD(TO_CHAR(ROUND(Grads.TCQA,2)*100),5,'0') TRAN_COMB_QUAL_HRS, --"Tran Cmb Quality Hours",  
  LPAD(TO_CHAR(ROUND(Grads.TCQP,2)*100),6,'0') TRAN_COMB_QUAL_PTS, --"Tran Cmb Quality Points",  
  CASE WHEN Grads.TCGPA < 1 THEN LPAD(REPLACE(TO_CHAR(ROUND(Grads.TCGPA,3)),'.'),4,'0') ELSE RPAD(REPLACE(TO_CHAR(ROUND(Grads.TCGPA,3)),'.'),4,'0')  END  TRAN_COMB_GPA, --"Tran Cmb GPA"
  LPAD(TO_CHAR(ROUND(Grads.OLHA,2)*100),5,'0') ALL_COLLEGE_HRS_ATMP, --"Over coL Hours Attempted",  
  LPAD(TO_CHAR(ROUND(Grads.OLHE,2)*100),5,'0') ALL_COLLEGE_HRS_EARN, --"Over coL Hours Earned",  
  LPAD(TO_CHAR(ROUND(Grads.OLQA,2)*100),5,'0') ALL_COLLEGE_QUAL_HRS, --"Over coL Quality Hours", 
  LPAD(TO_CHAR(ROUND(Grads.OLQP,2)*100),6,'0') ALL_COLLEGE_QUAL_PTS, --"Over coL Quality Points",  
  CASE WHEN Grads.OLGPA < 1 THEN LPAD(REPLACE(TO_CHAR(ROUND(Grads.OLGPA,3)),'.'),4,'0') ELSE RPAD(REPLACE(TO_CHAR(ROUND(Grads.OLGPA,3)),'.'),4,'0')  END  ALL_COLLEGE_GPA, --"Over coL GPA"
  LPAD(TO_CHAR(ROUND(Grads.ILHA,2)*100),5,'0') INST_COLLEGE_HRS_ATMP, --"Inst coL Hours Attempted",  
  LPAD(TO_CHAR(ROUND(Grads.ILHE,2)*100),5,'0') INST_COLLEGE_HRS_EARN, --"Inst coL Hours Earned",  
  LPAD(TO_CHAR(ROUND(Grads.ILQA,2)*100),5,'0') INST_COLLEGE_QUAL_HRS, --"Inst coL Quality Hours",  
  LPAD(TO_CHAR(ROUND(Grads.ILQP,2)*100),6,'0') INST_COLLEGE_QUAL_PTS, --"Inst coL Quality Points",  
  CASE WHEN Grads.iCGPA < 1 THEN LPAD(REPLACE(TO_CHAR(ROUND(Grads.ILGPA,3)),'.'),4,'0') ELSE RPAD(REPLACE(TO_CHAR(ROUND(Grads.ILGPA,3)),'.'),4,'0')  END  INST_COLLEGE_GPA, --"Inst coL GPA"
  LPAD(TO_CHAR(ROUND(Grads.TLHA,2)*100),5,'0') TRAN_COLLEGE_HRS_ATMP, --"Tran coL Hours Attempted", 
  LPAD(TO_CHAR(ROUND(Grads.TLHE,2)*100),5,'0') TRAN_COLLEGE_HRS_EARN, --"Tran coL Hours Earned",  
  LPAD(TO_CHAR(ROUND(Grads.TLQA,2)*100),5,'0') TRAN_COLLEGE_QUAL_HRS, --"Tran coL Quality Hours",  
  LPAD(TO_CHAR(ROUND(Grads.TLQP,2)*100),6,'0') TRAN_COLLEGE_QUAL_PTS, --"Tran coL Quality Points",  
  CASE WHEN Grads.TLGPA < 1 THEN LPAD(REPLACE(TO_CHAR(ROUND(Grads.TLGPA,3)),'.'),4,'0') ELSE RPAD(REPLACE(TO_CHAR(ROUND(Grads.TLGPA,3)),'.'),4,'0')  END  TRAN_COLLEGE_GPA, --"Tran coL GPA"
SPBPERS_ETHN_CDE ETHNICITY, NRC.RACE_UNKNOWN, NRC.RACE_ALASKAN_NATIVE, NRC.RACE_AMERICAN_INDIAN, NRC.RACE_ASIAN, NRC.RACE_BLACK_AFRICAN_AM, NRC.RACE_WHITE, NRC.RACE_HAWAIIAN_PAC_ISL,
GRADS.SHRDGMR_MAJR_CODE_1 FIRST_MAJOR_CODE,
GRADS.SHRDGMR_MAJR_CODE_CONC_1 FIRST_CONC_CODE,
S3.STVMAJR_CIPC_CODE FIRST_CONC_FED_CIP,
GRADS.SHRDGMR_MAJR_CODE_1_2 SECOND_MAJOR_CODE,
GRADS.SHRDGMR_MAJR_CODE_CONC_1_2 SECOND_CONC_CODE,
S4.STVMAJR_CIPC_CODE SECOND_CONC_FED_CIP
,GRADS.ReverseTransfer_Flag
-- 
  FROM SPRIDEN,SPBPERS,SGBSTDN,STVDEGC,STVMAJR S1,SORXREF X1,STVMAJR S2,SORXREF X2,STVMAJR S3,STVMAJR S4,
  (select GORPRAC_PIDM, 
  Max(CASE WHEN GORPRAC_RACE_CDE = '00' THEN GORPRAC_RACE_CDE ELSE NULL END) RACE_UNKNOWN, 
  Max(CASE WHEN GORPRAC_RACE_CDE = '10' THEN GORPRAC_RACE_CDE ELSE Null END) RACE_ALASKAN_NATIVE, 
  Max(CASE WHEN GORPRAC_RACE_CDE = '20' THEN GORPRAC_RACE_CDE ELSE NULL END) RACE_AMERICAN_INDIAN, 
  Max(CASE WHEN GORPRAC_RACE_CDE = '30' THEN GORPRAC_RACE_CDE ELSE NULL END) RACE_ASIAN, 
  Max(CASE WHEN GORPRAC_RACE_CDE = '40' THEN GORPRAC_RACE_CDE ELSE NULL END) RACE_BLACK_AFRICAN_AM, 
  MAX(CASE WHEN GORPRAC_RACE_CDE = '60' THEN GORPRAC_RACE_CDE ELSE NULL END) RACE_WHITE, 
  Max(CASE WHEN GORPRAC_RACE_CDE = '70' THEN GORPRAC_RACE_CDE ELSE NULL END) RACE_HAWAIIAN_PAC_ISL
  from gorprac group by gorprac_pidm) NRC, --New Race Code
-- 
  (SELECT SPRADDR_PIDM, 
                 substr(SPRADDR_CNTY_CODE,1,2),                         /*state-from county*/
		 substr(SPRADDR_CNTY_CODE,3,3),                         /*county*/
                 substr(SPRADDR_ZIP,1,5),                               /*zip */                                    
		 DECODE(SPRADDR_STAT_CODE, 'AL', '01',
                                           'AK', '02',
                                           'AZ', '04',
                                           'AR', '05',
                                           'CA', '06',
                                           'CO', '08',
                                           'CT', '09',
                                           'DE', '10',
                                           'DC', '11',
                                           'FL', '12',
                                           'GA', '13',
                                           'HI', '15',
                                           'ID', '16',
                                           'IL', '17',
                                           'IN', '18',
                                           'IA', '19',
                                           'KS', '20',
                                           'KY', '21',
                                           'LA', '22',
                                           'ME', '23',
                                           'MD', '24',
                                           'MA', '25',
                                           'MI', '26',
                                           'MN', '27',
                                           'MS', '28',
                                           'MO', '29',
                                           'MT', '30',
                                           'NE', '31',
                                           'NV', '32',
                                           'NH', '33',
                                           'NJ', '34',
                                           'NM', '35',
                                           'NY', '36',
                                           'NC', '37',
                                           'ND', '38',
                                           'OH', '39',
                                           'OK', '40',
                                           'OR', '41',
                                           'PA', '42',
                                           'RI', '44',
                                           'SC', '45',
                                           'SD', '46',
                                           'TN', '47',
                                           'TX', '48',
                                           'UT', '49',
                                           'VT', '50',
                                           'VA', '51',
                                           'WA', '53',
                                           'WV', '54',
                                           'WI', '55',
                                           'WY', '56', 
                                           'PR', 'RQ', SPRADDR_STAT_CODE)  STAT_CODE,           
		 DECODE(nvl(SPRADDR_NATN_CODE,'UNK'),  'WB', 'WE',
                                                       'MW', 'MJ',
                                                       'SR', 'RB', SPRADDR_NATN_CODE) NATN_CODE,
                 SPRADDR_CNTY_CODE CNTY_CODE
            FROM SPRADDR
           WHERE SPRADDR_ATYP_CODE = 'PR'
             AND SPRADDR_STATUS_IND IS NULL
             AND spraddr_from_date <= sysdate
             AND (spraddr_to_date  >= sysdate
              OR SPRADDR_TO_DATE IS NULL)) TT,
   (SELECT SHRDGMR_PIDM,SHRDGMR_TERM_CODE_GRAD,SHRDGMR_DEGC_CODE,SHRDGMR_MAJR_CODE_1,SHRDGMR_MAJR_CODE_CONC_1,SHRDGMR_MAJR_CODE_1_2,SHRDGMR_MAJR_CODE_CONC_1_2,SHRDGMR_CAMP_CODE,ReverseTransfer_Flag,
      SUM(OC_SHRTGPA_HOURS_ATTEMPTED) OCHA,
      SUM(OC_SHRTGPA_HOURS_EARNED) OCHE,
      SUM(OC_SHRTGPA_GPA_HOURS) OCQA,
      SUM(OC_SHRTGPA_QUALITY_POINTS) OCQP,
      CASE WHEN SUM(OC_SHRTGPA_GPA_HOURS)<> 0 THEN SUM(OC_SHRTGPA_QUALITY_POINTS)/SUM(OC_SHRTGPA_GPA_HOURS) END OCGPA,
      SUM(IC_SHRTGPA_HOURS_ATTEMPTED) ICHA,
      SUM(IC_SHRTGPA_HOURS_EARNED) ICHE,
      SUM(IC_SHRTGPA_GPA_HOURS) ICQA,
      SUM(IC_SHRTGPA_QUALITY_POINTS) ICQP,
      CASE WHEN SUM(IC_SHRTGPA_GPA_HOURS)<> 0 THEN SUM(IC_SHRTGPA_QUALITY_POINTS)/SUM(IC_SHRTGPA_GPA_HOURS) END ICGPA,
      SUM(TC_SHRTGPA_HOURS_ATTEMPTED) TCHA, 
      SUM(TC_SHRTGPA_HOURS_EARNED) TCHE, 
      SUM(TC_SHRTGPA_GPA_HOURS) TCQA, 
      SUM(TC_SHRTGPA_QUALITY_POINTS) TCQP, 
      CASE WHEN SUM(TC_SHRTGPA_GPA_HOURS)<> 0 THEN SUM(TC_SHRTGPA_QUALITY_POINTS)/SUM(TC_SHRTGPA_GPA_HOURS) END TCGPA,  
      SUM(OL_SHRTGPA_HOURS_ATTEMPTED) OLHA,  
      SUM(OL_SHRTGPA_HOURS_EARNED) OLHE,  
      SUM(OL_SHRTGPA_GPA_HOURS) OLQA,  
      SUM(OL_SHRTGPA_QUALITY_POINTS) OLQP,  
      CASE WHEN SUM(OL_SHRTGPA_GPA_HOURS)<> 0 THEN SUM(OL_SHRTGPA_QUALITY_POINTS)/SUM(OL_SHRTGPA_GPA_HOURS) END OLGPA,  
      SUM(IL_SHRTGPA_HOURS_ATTEMPTED) ILHA,  
      SUM(IL_SHRTGPA_HOURS_EARNED) ILHE,  
      SUM(IL_SHRTGPA_GPA_HOURS) ILQA,  
      SUM(IL_SHRTGPA_QUALITY_POINTS) ILQP,  
      CASE WHEN SUM(IL_SHRTGPA_GPA_HOURS)<> 0 THEN SUM(IL_SHRTGPA_QUALITY_POINTS)/SUM(IL_SHRTGPA_GPA_HOURS) END ILGPA,  
      SUM(TL_SHRTGPA_HOURS_ATTEMPTED) TLHA,  
      SUM(TL_SHRTGPA_HOURS_EARNED) TLHE, 
      SUM(TL_SHRTGPA_GPA_HOURS) TLQA, 
      SUM(TL_SHRTGPA_QUALITY_POINTS) TLQP, 
      CASE WHEN SUM(TL_SHRTGPA_GPA_HOURS)<> 0 THEN SUM(TL_SHRTGPA_QUALITY_POINTS)/SUM(TL_SHRTGPA_GPA_HOURS) END TLGPA,  
      MAX(SHRTGPA_TERM_CODE) Term_Of_Completion
      FROM
          (SELECT DISTINCT SHRDGMR_PIDM,SHRDGMR_TERM_CODE_GRAD,SHRDGMR_DEGC_CODE,SHRDGMR_MAJR_CODE_1,SHRDGMR_MAJR_CODE_1_2,SHRDGMR_MAJR_CODE_CONC_1,SHRDGMR_MAJR_CODE_CONC_1_2,
            CASE WHEN SHRTGPA_GPA_TYPE_IND IN('C','W') THEN SHRTGPA_HOURS_ATTEMPTED ELSE NULL END  OC_SHRTGPA_HOURS_ATTEMPTED, 
            CASE WHEN SHRTGPA_GPA_TYPE_IND IN('C','W') THEN SHRTGPA_HOURS_EARNED ELSE NULL END  OC_SHRTGPA_HOURS_EARNED, 
            CASE WHEN SHRTGPA_GPA_TYPE_IND IN('C','W') THEN SHRTGPA_GPA_HOURS ELSE NULL END OC_SHRTGPA_GPA_HOURS, 
            CASE WHEN SHRTGPA_GPA_TYPE_IND IN('C','W') THEN SHRTGPA_QUALITY_POINTS ELSE NULL END  OC_SHRTGPA_QUALITY_POINTS,  
            CASE WHEN SHRTGPA_GPA_TYPE_IND IN('C') THEN SHRTGPA_HOURS_ATTEMPTED ELSE NULL END IC_SHRTGPA_HOURS_ATTEMPTED,
            CASE WHEN SHRTGPA_GPA_TYPE_IND IN('C') THEN SHRTGPA_HOURS_EARNED ELSE NULL END IC_SHRTGPA_HOURS_EARNED,
            CASE WHEN SHRTGPA_GPA_TYPE_IND IN('C') THEN SHRTGPA_GPA_HOURS ELSE NULL END IC_SHRTGPA_GPA_HOURS,
            CASE WHEN SHRTGPA_GPA_TYPE_IND IN('C') THEN SHRTGPA_QUALITY_POINTS ELSE NULL END IC_SHRTGPA_QUALITY_POINTS,
            CASE WHEN SHRTGPA_GPA_TYPE_IND IN('W') THEN SHRTGPA_HOURS_ATTEMPTED ELSE NULL END TC_SHRTGPA_HOURS_ATTEMPTED,  
            CASE WHEN SHRTGPA_GPA_TYPE_IND IN('W') THEN SHRTGPA_HOURS_EARNED ELSE NULL END TC_SHRTGPA_HOURS_EARNED,  
            CASE WHEN SHRTGPA_GPA_TYPE_IND IN('W') THEN SHRTGPA_GPA_HOURS ELSE NULL END TC_SHRTGPA_GPA_HOURS,   
            CASE WHEN SHRTGPA_GPA_TYPE_IND IN('W') THEN SHRTGPA_QUALITY_POINTS ELSE NULL END TC_SHRTGPA_QUALITY_POINTS,  
            CASE WHEN SHRTGPA_GPA_TYPE_IND IN('I','T') THEN SHRTGPA_HOURS_ATTEMPTED ELSE NULL END  OL_SHRTGPA_HOURS_ATTEMPTED, 
            CASE WHEN SHRTGPA_GPA_TYPE_IND IN('I','T') THEN SHRTGPA_HOURS_EARNED ELSE NULL END  OL_SHRTGPA_HOURS_EARNED, 
            CASE WHEN SHRTGPA_GPA_TYPE_IND IN('I','T') THEN SHRTGPA_GPA_HOURS ELSE NULL END OL_SHRTGPA_GPA_HOURS,
            CASE WHEN SHRTGPA_GPA_TYPE_IND IN('I','T') THEN SHRTGPA_QUALITY_POINTS ELSE NULL END  OL_SHRTGPA_QUALITY_POINTS,  
            CASE WHEN SHRTGPA_GPA_TYPE_IND IN('I') THEN SHRTGPA_HOURS_ATTEMPTED ELSE NULL END IL_SHRTGPA_HOURS_ATTEMPTED,  
            CASE WHEN SHRTGPA_GPA_TYPE_IND IN('I') THEN SHRTGPA_HOURS_EARNED ELSE NULL END IL_SHRTGPA_HOURS_EARNED,  
            CASE WHEN SHRTGPA_GPA_TYPE_IND IN('I') THEN SHRTGPA_GPA_HOURS ELSE NULL END IL_SHRTGPA_GPA_HOURS,  
            CASE WHEN SHRTGPA_GPA_TYPE_IND IN('I') THEN SHRTGPA_QUALITY_POINTS ELSE NULL END IL_SHRTGPA_QUALITY_POINTS,  
            CASE WHEN SHRTGPA_GPA_TYPE_IND IN('T') THEN SHRTGPA_HOURS_ATTEMPTED ELSE NULL END TL_SHRTGPA_HOURS_ATTEMPTED,  
            CASE WHEN SHRTGPA_GPA_TYPE_IND IN('T') THEN SHRTGPA_HOURS_EARNED ELSE NULL END TL_SHRTGPA_HOURS_EARNED, 
            CASE WHEN SHRTGPA_GPA_TYPE_IND IN('T') THEN SHRTGPA_GPA_HOURS ELSE NULL END TL_SHRTGPA_GPA_HOURS,    
            CASE WHEN SHRTGPA_GPA_TYPE_IND IN('T') THEN SHRTGPA_QUALITY_POINTS ELSE NULL END TL_SHRTGPA_QUALITY_POINTS,  
            SHRDGMR_CAMP_CODE,SHRTGPA_TERM_CODE, SHRTGPA_GPA_TYPE_IND      
            ,case when SHRDGMR_GRST_CODE = 'RTS' then '1' end as ReverseTransfer_Flag --9/2016 updated to char
            FROM SHRDGMR,SHRTGPA
            WHERE 
            SUBSTR(SHRDGMR_TERM_CODE_GRAD,1,5) IN (&GradYear||'1',  --for APSU terms
                   SUBSTR(To_Char(TO_Number(&GradYear||'10')-30),1,5),  --for APSU terms
                   SUBSTR(To_Char(TO_Number(&GradYear||'10')-60),1,5)) --for APSU terms
            AND SUBSTR(SHRDGMR_TERM_CODE_GRAD,6,1) NOT IN ('8', '9')  --for APSU terms             
            /* SHRDGMR_TERM_CODE_GRAD IN (&GradYear||'10',To_Char(TO_Number(&GradYear||'10')-30),To_Char(TO_Number(&GradYear||'10')-60)) */
            AND SHRDGMR_DEGS_CODE = 'AW'
            AND SHRTGPA_PIDM = SHRDGMR_PIDM
            AND SHRTGPA_TERM_CODE <= SHRDGMR_TERM_CODE_GRAD
            AND SHRTGPA_LEVL_CODE = SHRDGMR_LEVL_CODE
            AND SHRTGPA_HOURS_ATTEMPTED > 0
            )
      GROUP BY SHRDGMR_PIDM,SHRDGMR_TERM_CODE_GRAD,SHRDGMR_DEGC_CODE,SHRDGMR_MAJR_CODE_1,SHRDGMR_MAJR_CODE_1_2,SHRDGMR_MAJR_CODE_CONC_1,SHRDGMR_MAJR_CODE_CONC_1_2,SHRDGMR_CAMP_CODE,ReverseTransfer_Flag
    ) Grads, 
    (Select X.SORHSCH_PIDM, X.SORHSCH_SBGI_CODE, X.SORHSCH_GRADUATION_DATE, X.SORHSCH_CLASS_RANK, X.SORHSCH_CLASS_SIZE, X.SORHSCH_PERCENTILE, X.SORHSCH_DPLM_CODE, X.SORHSCH_GPA  
     From SORHSCH X,
    --first subquery HS 
          (SELECT H.SORHSCH_PIDM PIDM, max(H.SORHSCH_SBGI_CODE) Max_SBGI_Code, AA.Max_Activity_Date Max_Activity_Date, AA.Max_Graduation_Date Max_Graduation_Date, AA.Max_GPA Max_GPA FROM SORHSCH H,
           -- second subquery AA   
            (Select A.SORHSCH_PIDM PIDM, Max(A.SORHSCH_Activity_Date) Max_Activity_Date, BB.Max_Graduation_Date Max_Graduation_Date, BB.Max_GPA Max_GPA  From  SORHSCH A, 
                 --third Subquery BB 
                 (Select B.SORHSCH_PIDM PIDM, nvl(Max(B.SORHSCH_GPA), 'None') Max_GPA, CC.Max_Graduation_Date Max_Graduation_Date From SORHSCH B,
                       --fourth Subquery CC 
                       (Select C.SORHSCH_PIDM PIDM, nvl(to_char(Max(C.sorhsch_Graduation_Date)),'None') Max_Graduation_Date From SORHSCH C Group By C.SORHSCH_PIDM) CC
                  --BB Where 
                  Where B.SORHSCH_PIDM = CC.PIDM And nvl(to_char(B.SORHSCH_Graduation_Date),'None') = CC.Max_Graduation_Date Group By B.SORHSCH_PIDM, CC.Max_Graduation_Date) BB
            --AA Where 
            Where A.SORHSCH_PIDM = BB.PIDM And nvl(to_char(A.SORHSCH_Graduation_Date),'None') = BB.Max_Graduation_Date And nvl(A.SORHSCH_GPA,'None') = BB.Max_Gpa 
            --AA Group By 
            Group By A.SORHSCH_PIDM, BB.Max_Gpa, BB.Max_Graduation_Date) AA
            --HS Where 
            WHERE H.SORHSCH_PIDM = AA.PIDM and nvl(to_char(H.SORHSCH_GRADUATION_DATE),'None') = AA.Max_Graduation_Date And nvl(H.SORHSCH_GPA, 'None') = AA.Max_Gpa And H.SORHSCH_Activity_Date = AA.Max_Activity_Date
            --HS Group By 
            GROUP BY H.SORHSCH_PIDM, AA.Max_Activity_Date, AA.Max_Gpa, AA.Max_Graduation_Date) HS
    --Main query Where 
    Where X.SORHSCH_PIDM = HS.PIDM And X.SORHSCH_SBGI_CODE = HS.Max_SBGI_Code AND nvl(to_char(X.SORHSCH_Graduation_Date),'None') = HS.Max_Graduation_Date And nvl(X.SORHSCH_GPA, 'None') = HS.Max_Gpa And X.SORHSCH_Activity_Date = HS.Max_Activity_Date ) XX  
--                                                                                             
  WHERE Grads.SHRDGMR_PIDM = SPRIDEN_PIDM AND SPRIDEN_CHANGE_IND  IS NULL
  AND Grads.SHRDGMR_PIDM = TT.SPRADDR_PIDM(+)  
  AND Grads.SHRDGMR_PIDM = SPBPERS_PIDM
  AND Grads.SHRDGMR_PIDM = SGBSTDN_PIDM
  AND Grads.SHRDGMR_PIDM = NRC.GORPRAC_PIDM(+)
  AND SGBSTDN_TERM_CODE_EFF = 
  (SELECT MAX(A.SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN A
    WHERE A.SGBSTDN_TERM_CODE_EFF <= SHRDGMR_TERM_CODE_GRAD
    AND A.SGBSTDN_PIDM = SGBSTDN.SGBSTDN_PIDM
  )
  AND Grads.SHRDGMR_PIDM = XX.SORHSCH_PIDM(+)
  AND STVDEGC_CODE(+) = Grads.SHRDGMR_DEGC_CODE
  AND S1.STVMAJR_CODE(+) = Grads.SHRDGMR_MAJR_CODE_1
  AND X1.SORXREF_BANNER_VALUE(+) = Grads.SHRDGMR_DEGC_CODE || Grads.SHRDGMR_MAJR_CODE_1
  AND X1.SORXREF_XLBL_CODE(+) = 'TBRCIPC'
  AND S2.STVMAJR_CODE(+) = Grads.SHRDGMR_MAJR_CODE_1_2
  AND X2.SORXREF_BANNER_VALUE(+) = Grads.SHRDGMR_DEGC_CODE || Grads.SHRDGMR_MAJR_CODE_1_2
  AND X2.SORXREF_XLBL_CODE(+) = 'TBRCIPC'
  AND S3.STVMAJR_CODE(+) = GRADS.SHRDGMR_MAJR_CODE_CONC_1
  AND S4.STVMAJR_CODE(+) = Grads.SHRDGMR_MAJR_CODE_CONC_1_2
  ORDER By STUDENT_ID_NUMBER, AWARD, FIRST_MAJOR_AREA;
--Set items
SPOOL OFF
SET ECHO ON
SET VERIFY ON
SET FEEDBACK ON
SET HEADING ON




