SELECT SPRIDEN.SPRIDEN_ID BannerID,
  SPRIDEN.SPRIDEN_LAST_NAME LNAME,
  SPRIDEN.SPRIDEN_FIRST_NAME FNAME,
  SPRIDEN.SPRIDEN_MI MNAME,
  VETN.SGRVETN_VETC_CODE AS VETCODE,
  VETN.STVVETC_DESC      AS CHAPTER,
  PYMT.TBRACCD_TERM_CODE AS PMTTERM,
  PYMT.TBBDETC_DESC      AS PMTDESC,
  PYMT.PMTAMT
FROM SPRIDEN
INNER JOIN
  (SELECT DISTINCT V1.SGRVETN_PIDM,
    V1.SGRVETN_VETC_CODE,
    SATURN.STVVETC.STVVETC_DESC,
    V1.SGRVETN_CERT_DATE,
    V1.SGRVETN_CERT_HOURS,
    V1.SGRVETN_TERM_CODE_VA
  FROM sgrvetn V1
  INNER JOIN SATURN.STVVETC
  ON V1.SGRVETN_VETC_CODE     = SATURN.STVVETC.STVVETC_CODE
  WHERE V1.SGRVETN_VETC_CODE  = 'T'
  AND V1.SGRVETN_TERM_CODE_VA =
    (SELECT MAX(V2.SGRVETN_TERM_CODE_VA)
    FROM sgrvetn V2
    WHERE V2.SGRVETN_PIDM        = V1.SGRVETN_PIDM
    AND V2.SGRVETN_TERM_CODE_VA <= :DD_TermCode.TermCode
    )
  ) VETN ON SPRIDEN.SPRIDEN_PIDM = VETN.SGRVETN_PIDM
INNER JOIN
  (SELECT tbraccd.TBRACCD_PIDM,
    tbraccd.TBRACCD_TERM_CODE,
    tbraccd.TBRACCD_DETAIL_CODE,
    tbbdetc.TBBDETC_DESC,
    SUM(tbraccd.TBRACCD_AMOUNT) AS PMTAMT
  FROM tbraccd
  INNER JOIN tbbdetc
  ON tbraccd.TBRACCD_DETAIL_CODE  = tbbdetc.TBBDETC_DETAIL_CODE
  WHERE TBRACCD.TBRACCD_TERM_CODE = :DD_TermCode.TermCode
  AND tbbdetc.TBBDETC_TYPE_IND    = 'P'
  GROUP BY tbraccd.TBRACCD_PIDM,
    tbraccd.TBRACCD_TERM_CODE,
    tbraccd.TBRACCD_DETAIL_CODE,
    tbbdetc.TBBDETC_DESC
  ) PYMT ON VETN.SGRVETN_PIDM     = PYMT.TBRACCD_PIDM
WHERE SPRIDEN.SPRIDEN_CHANGE_IND IS NULL
ORDER BY SPRIDEN.SPRIDEN_LAST_NAME,
  SPRIDEN.SPRIDEN_FIRST_NAME,
  SPRIDEN.SPRIDEN_MI
